title: By Sound Alone
author: Mark Torrey # name of site's author
email: grannycart@protonmail.com # email of site's author
url: https://bysoundalone.net # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if your site shouldn't use a subpath)
description: An open-source and free novel with cargo submarines. <br> Also a pigeon.

# permalink: /:slug.html

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
goat_counter: "bysoundalone" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  #back_home_text: ".." # commented because I have a custom back_home.html file in _includes
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

posts: _posts # location of posts for xml feed

kramdown: # need to disable smart typography for rss feed to work properly
  # This sets all site " and ' to typewriter style, which at least looks fine with my site/typeface:
  smart_quotes:               apos,apos,quot,quot
  # This sets emdashes (---) to use html &mdash;. And ellipse to html ellipse
  typographic_symbols:        {mdash: "&mdash;", hellip: "&hellip;"}

plugins:
  - jekyll-feed
  - jekyll-seo-tag






